// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFcB6A_BbN6vVeXwwyEmyjvRazpx2162E',
    appId: '1:763389861619:web:0818ec2160e64b9e9b6186',
    messagingSenderId: '763389861619',
    projectId: 'hoor-store-8c045',
    authDomain: 'hoor-store-8c045.firebaseapp.com',
    storageBucket: 'hoor-store-8c045.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2I5fEDoQar-bD0I8XTRZ9R7UoIFZwUo',
    appId: '1:763389861619:android:f66094818b30e2979b6186',
    messagingSenderId: '763389861619',
    projectId: 'hoor-store-8c045',
    storageBucket: 'hoor-store-8c045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWcyLgL9kOEN-SfESTqzr1v3L32iD7Qfc',
    appId: '1:763389861619:ios:771b493de8bf18f79b6186',
    messagingSenderId: '763389861619',
    projectId: 'hoor-store-8c045',
    storageBucket: 'hoor-store-8c045.appspot.com',
    androidClientId: '763389861619-nkgojhv2dhf416blqnhrj8fjdodj85lg.apps.googleusercontent.com',
    iosClientId: '763389861619-rj38mijb0bdcudushhqd1hefib5a1ogp.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.sixamMart',
  );
}
